rosewater: &rosewater "#f5e0dc"

flamingo: &flamingo "#f2cdcd"
pink: &pink "#f5c2e7"
mauve: &mauve "#cba6f7"
red: &red "#f38ba8"
maroon: &maroon "#eba0ac"
peach: &peach "#fab387"
yellow: &yellow "#f9e2af"
green: &green "#a6e3a1"
teal: &teal "#94e2d5"
sky: &sky "#89dceb"
sapphire: &sapphire "#74c7ec"
blue: &blue "#89b4fa"
lavender: &lavender "#b4befe"
text: &text "#cdd6f4"

subtext1: &subtext1 "#bac2de"
subtext0: &subtext0 "#a6adc8"
overlay2: &overlay2 "#9399b2"
overlay1: &overlay1 "#7f849c"
overlay0: &overlay0 "#6c7086"
surface2: &surface2 "#585b70"
surface1: &surface1 "#45475a"
surface0: &surface0 "#313244"

base: &base "#1e1e2e"
mantle: &mantle "#181825"
crust: &crust "#11111b"
crust_tp: &crust_tp "#11111bcc"

general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Cursor jump settings (added from the modern version).
  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: false # Set to true if you want cursor jumping enabled.

    # Trigger for cursor jump.
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "window_focus"

  # Whether to show floating windows as always on top.
  show_floating_on_top: false

  # Amount to move floating windows by (e.g., when using `alt+<hjkl>` on a floating window).
  floating_window_move_amount: "5%"

  # Whether to center new floating windows.
  center_new_floating_windows: true

  # Whether to globally enable/disable window transition animations (on minimize, close, etc.).
  window_animations: "unchanged"

gaps:
  # Gap between adjacent windows.
  inner_gap: "2px"

  # Gap between windows and the screen edge.
  outer_gap:
    top: "1px"
    right: "1px"
    bottom: "1px"
    left: "1px"

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#0000ff"

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: "#ff0000"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

bar:
  height: "28px"
  position: "top"
  opacity: 1.0
  background: *crust_tp
  foreground: *blue
  font_family: "JetBrainsMono Nerd Font"
  font_size: "13px"
  padding: "4px 6px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  component_separator:
    label: "  "
  components_left:
    #- type: "tiling direction"
    #  label_horizontal: "⮂"
    #  label_vertical: "⮁"
    #  background: *crust_tp
    #  margin: "0 4px"
    #  padding: "0 8px"
    - type: "workspaces"
      focused_workspace_background: *blue
      focused_workspace_foreground: *crust

      displayed_workspace_background: *surface0
      default_workspace_background: "transparent"
    - type: "music"

      label_not_playing: " --  --"
      label_paused: " {song_title} - {artist_name}"
      label_playing: "  {song_title} - {artist_name}"

      max_title_length: 30
      max_artist_length: 20
    - type: "volume"
      label_low: " {volume_level}%"
      label_medium: " {volume_level}%"
      label_high: " {volume_level}%"
      label_mute: " {volume_level}%"
  components_center:
    - type: "window title"
  components_right:
    - type: "system tray"
    # - type: "system tray"
    #- type: "network"
    #  label_no_internet: "NC"
    #  label_ethernet: "Eth"
    #  label_wifi_strength0: "WiFi: 0%"
    #  label_wifi_strength25: "WiFi: 25%"
    #  label_wifi_strength50: "WiFi: 50%"
    #  label_wifi_strength75: "WiFi: 75%"
    #  label_wifi_strength100: "WiFi: 100%"
    - type: "clock"
      # Documentation on formatting date/time string:

      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      # time_formatting: "hh:mm tt  ddd MMM d"
      time_formatting: "yyyy-dd-MM HH:mm"

workspaces:
  - name: "1"
    # display_name: "󰋞"
    display_name: "home"
    keep_alive: true
  - name: "2"
    # display_name: "" # centered, small
    # display_name: ""
    display_name: "web"

  - name: "3"
    # display_name: ""
    # display_name: ""
    # display_name: ""

    display_name: "comms"

  - name: "4"
    # display_name: "󰂺"
    # display_name: ""
  - name: "5"
    # display_name: ""
  - name: "6"
    # display_name: ""
  - name: "7"
    # display_name: ""

  - name: "8"
    # display_name: ""
  - name: "9"
    # display_name: ""

window_rules:
  - commands: ["ignore"]
    match:
      # Ignores Task Manager and ScreenClippingHost windows.
      - window_process: { regex: "Taskmgr|ScreenClippingHost" }

  - commands: ["set-floating --shown-on-top"]
    match:
      - window_class: { equals: "#32770" }

  - commands: ["ignore"]
    match:
      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }

  - commands: ["resize --width -7%"]
    match:
      - window_process: { equals: "steam" }

  - commands: ["ignore"]
    match:
      - window_process:
          { regex: "eso64|DaggerfallUnity|valheim|OpenMW|openmw|openmw.exe" }

  - commands: ["move --workspace 2"]
    match:
      - window_process: { regex: "firefox|thorium" }

  - commands: ["move --workspace 3"]
    match:
      - window_process: { regex: "Discord|mailspring|slack" }

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - commands: ["resize --width -2%"]
        bindings: ["H", "Left"]
      - commands: ["resize --width +2%"]
        bindings: ["L", "Right"]
      - commands: ["resize --height +2%"]
        bindings: ["K", "Up"]
      - commands: ["resize --height -2%"]
        bindings: ["J", "Down"]
      # Press enter/escape to return to default keybindings.
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["Escape", "Enter"]

keybindings:
  - commands:
      ["shell-exec C:\\Program Files\\Thorium\\Application\\thorium.exe"]
    bindings: ["Alt+B"]
  - commands: ["shell-exec wt"]
    bindings: ["Alt+X"]
  - commands: ["shell-exec explorer"]
    bindings: ["Alt+E"]
  - commands: ["shell-exec %LOCALAPPDATA%\\Programs\\cursor\\Cursor.exe"]
    bindings: ["Alt+W"]
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["Alt+H", "Alt+Left"]
  - commands: ["focus --direction right"]
    bindings: ["Alt+L", "Alt+Right"]
  - commands: ["focus --direction up"]
    bindings: ["Alt+K", "Alt+Up"]
  - commands: ["focus --direction down"]
    bindings: ["Alt+J", "Alt+Down"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["Alt+Shift+H", "Alt+Shift+Left"]
  - commands: ["move --direction right"]
    bindings: ["Alt+Shift+L", "Alt+Shift+Right"]
  - commands: ["move --direction up"]
    bindings: ["Alt+Shift+K", "Alt+Shift+Up"]
  - commands: ["move --direction down"]
    bindings: ["Alt+Shift+J", "Alt+Shift+Down"]

  # Change window split direction (eg. from horizontal to vertical).
  - commands: ["toggle-tiling-direction"]
    bindings: ["Alt+Return"]

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2%"]

    bindings: ["Alt+U"]
  - commands: ["resize --width +2%"]
    bindings: ["Alt+P"]
  - commands: ["resize --height +2%"]
    bindings: ["Alt+O"]
  - commands: ["resize --height -2%"]
    bindings: ["Alt+I"]

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["Alt+R"]

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - commands: ["toggle-tiling-direction"]
    bindings: ["Alt+V"]

  # Change focus between floating / tiling windows.
  - commands: ["wm-cycle-focus"]
    bindings: ["Alt+Space"]

  # Change the focused window to be floating / tiling.
  - commands: ["toggle-floating --centered"]
    bindings: ["Alt+Shift+Space"]

  # Change the focused window to be maximized / unmaximized.
  - commands: ["toggle-minimized"]
    bindings: ["Alt+X"]

  # Close focused window.

  - commands: ["close"]
    bindings: ["Alt+Q"]

  # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["Alt+Shift+E"]

  # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["Alt+Shift+R"]

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - commands: ["shell-exec cmd"]
    bindings: ["Alt+Enter"]

  # Focus the workspace that last had focus.
  - commands: ["focus --recent-workspace"]
    bindings: ["Alt+Y"]

  # Focus the next/previous workspace defined in `workspaces` config.
  - commands: ["focus --next-workspace"]
    bindings: ["Alt+T"]
  - commands: ["focus --prev-workspace"]
    bindings: ["Alt+Shift+T"]

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace 1"]
    bindings: ["Alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["Alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["Alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["Alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["Alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["Alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["Alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["Alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["Alt+9"]

  # Move focused workspace to a monitor in a given direction.
  - commands: ["move-workspace --direction left"]
    bindings: ["Alt+A"]
  - commands: ["move-workspace --direction right"]
    bindings: ["Alt+F"]
  - commands: ["move-workspace --direction up"]
    bindings: ["Alt+D"]
  - commands: ["move-workspace --direction down"]
    bindings: ["Alt+S"]

  # Move focused window to a workspace defined in `workspaces` config.

  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["Alt+Shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["Alt+Shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["Alt+Shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["Alt+Shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["Alt+Shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["Alt+Shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["Alt+Shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["Alt+Shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["Alt+Shift+9"]

  # Cycle focus between open windows in the focused workspace.
  #- commands: ["focus --next-workspace"]
  #  bindings: ["Alt+Tab"]
  #- commands: ["focus --prev-workspace"]
  #  bindings: ["Alt+Shift+Tab"]

  # Launch the keybinding helper popup.
  #- commands: ["binding mode keybindings"]
  #  bindings: ["Alt+G"]
